# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.x/metricbeat-module-kibana.html

- module: kibana
  xpack.enabled: true
  period: 60s
  hosts: ["https://kibana:5601"]
  basepath: "/kibana"
  username: "elastic"
  password: "changeme"
  ssl.certificate_authorities: "/usr/share/certificates/ca/ca.crt"
  ssl.certificate: "/usr/share/certificates/metricbeat/metricbeat.crt"
  ssl.key: "/usr/share/certificates/metricbeat/metricbeat.key"

